#############################################################################
# Makefile for building: SpecPlot
# Generated by qmake (2.01a) (Qt 4.6.2) on: mer. juil. 28 23:58:56 2010
# Project:  SpecPlot.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile SpecPlot.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtMultimedia -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib /usr/lib/libqwt.so.5 /usr/lib/libfftw3.a /usr/lib/libfftw3f.a /usr/lib/libfftw3l.a -lQtMultimedia -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		canvaspicker.cpp \
		wavfile.cpp \
		specplot.cpp \
		specbox.cpp moc_mainwindow.cpp \
		moc_specplot.cpp \
		moc_wavfile.cpp \
		moc_specbox.cpp \
		moc_canvaspicker.cpp
OBJECTS       = main.o \
		mainwindow.o \
		canvaspicker.o \
		wavfile.o \
		specplot.o \
		specbox.o \
		moc_mainwindow.o \
		moc_specplot.o \
		moc_wavfile.o \
		moc_specbox.o \
		moc_canvaspicker.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		SpecPlot.pro
QMAKE_TARGET  = SpecPlot
DESTDIR       = 
TARGET        = SpecPlot

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SpecPlot.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtMultimedia.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile SpecPlot.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtMultimedia.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile SpecPlot.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SpecPlot1.0.0 || $(MKDIR) .tmp/SpecPlot1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SpecPlot1.0.0/ && $(COPY_FILE) --parents mainwindow.h specplot.h specplot.h wavfile.h specbox.h canvaspicker.h .tmp/SpecPlot1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp canvaspicker.cpp wavfile.cpp specplot.cpp specbox.cpp .tmp/SpecPlot1.0.0/ && (cd `dirname .tmp/SpecPlot1.0.0` && $(TAR) SpecPlot1.0.0.tar SpecPlot1.0.0 && $(COMPRESS) SpecPlot1.0.0.tar) && $(MOVE) `dirname .tmp/SpecPlot1.0.0`/SpecPlot1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SpecPlot1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_specplot.cpp moc_specplot.cpp moc_wavfile.cpp moc_specbox.cpp moc_canvaspicker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_specplot.cpp moc_specplot.cpp moc_wavfile.cpp moc_specbox.cpp moc_canvaspicker.cpp
moc_mainwindow.cpp: specbox.h \
		specplot.h \
		/usr/include/qt4/QtMultimedia/QAudioOutput \
		/usr/include/qt4/QtMultimedia/qaudiooutput.h \
		wavfile.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_specplot.cpp: specplot.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) specplot.h -o moc_specplot.cpp

moc_specplot.cpp: specplot.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) specplot.h -o moc_specplot.cpp

moc_wavfile.cpp: wavfile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wavfile.h -o moc_wavfile.cpp

moc_specbox.cpp: specplot.h \
		specbox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) specbox.h -o moc_specbox.cpp

moc_canvaspicker.cpp: canvaspicker.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) canvaspicker.h -o moc_canvaspicker.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		specbox.h \
		specplot.h \
		/usr/include/qt4/QtMultimedia/QAudioOutput \
		/usr/include/qt4/QtMultimedia/qaudiooutput.h \
		wavfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		specbox.h \
		specplot.h \
		/usr/include/qt4/QtMultimedia/QAudioOutput \
		/usr/include/qt4/QtMultimedia/qaudiooutput.h \
		wavfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

canvaspicker.o: canvaspicker.cpp canvaspicker.h \
		specplot.h \
		specbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canvaspicker.o canvaspicker.cpp

wavfile.o: wavfile.cpp wavfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wavfile.o wavfile.cpp

specplot.o: specplot.cpp specplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specplot.o specplot.cpp

specbox.o: specbox.cpp specbox.h \
		specplot.h \
		mainwindow.h \
		/usr/include/qt4/QtMultimedia/QAudioOutput \
		/usr/include/qt4/QtMultimedia/qaudiooutput.h \
		wavfile.h \
		canvaspicker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specbox.o specbox.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_specplot.o: moc_specplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specplot.o moc_specplot.cpp

moc_wavfile.o: moc_wavfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wavfile.o moc_wavfile.cpp

moc_specbox.o: moc_specbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specbox.o moc_specbox.cpp

moc_canvaspicker.o: moc_canvaspicker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_canvaspicker.o moc_canvaspicker.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

